# Generated by Django 4.2.21 on 2025-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('freezed', 'Freezed'), ('pending', 'Pending')], default='open', max_length=15),
        ),
    ]
